const regionsData = {
  "United States": ["united states"],
  Canada: ["canada"],
  "United Kingdom": ["united kingdom"],
  Europe: [
    "albania",
    "andorra",
    "armenia",
    "austria",
    "azerbaijan",
    "belarus",
    "belgium",
    "bosnia and herzegovina",
    "bulgaria",
    "croatia",
    "cyprus",
    "czech republic",
    "denmark",
    "estonia",
    "finland",
    "france",
    "georgia",
    "germany",
    "greece",
    "hungary",
    "iceland",
    "ireland",
    "italy",
    "kazakhstan",
    "kosovo",
    "latvia",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "malta",
    "moldova",
    "monaco",
    "montenegro",
    "netherlands",
    "north macedonia",
    "norway",
    "poland",
    "portugal",
    "romania",
    "russia",
    "san marino",
    "serbia",
    "slovakia",
    "slovenia",
    "spain",
    "sweden",
    "switzerland",
    "turkey",
    "ukraine",
    "vatican city",
  ],

  "Middle East": [
    "bahrain",
    "cyprus",
    "egypt",
    "iran",
    "iraq",
    "israel",
    "jordan",
    "kuwait",
    "lebanon",
    "oman",
    "palestine",
    "qatar",
    "saudi arabia",
    "syria",
    "turkey",
    "uae",
    "yemen",
  ],

  Asia: [
    "afghanistan",
    "armenia",
    "azerbaijan",
    "bangladesh",
    "bhutan",
    "brunei",
    "cambodia",
    "china",
    "east timor",
    "georgia",
    "hong kong",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "israel",
    "japan",
    "jordan",
    "kazakhstan",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "lebanon",
    "malaysia",
    "maldives",
    "mongolia",
    "myanmar",
    "nepal",
    "north korea",
    "oman",
    "pakistan",
    "palestine",
    "philippines",
    "qatar",
    "saudi arabia",
    "singapore",
    "south korea",
    "sri lanka",
    "syria",
    "taiwan",
    "tajikistan",
    "thailand",
    "turkmenistan",
    "uae",
    "uzbekistan",
    "vietnam",
    "yemen",
  ],

  Africa: [
    "algeria",
    "angola",
    "benin",
    "botswana",
    "burkina faso",
    "burundi",
    "cabo verde",
    "cameroon",
    "central african republic",
    "chad",
    "comoros",
    "congo (brazzaville)",
    "congo (kinshasa)",
    "côte d’ivoire",
    "djibouti",
    "egypt",
    "equatorial guinea",
    "eritrea",
    "eswatini",
    "ethiopia",
    "gabon",
    "gambia",
    "ghana",
    "guinea",
    "guinea-bissau",
    "kenya",
    "lesotho",
    "liberia",
    "libya",
    "madagascar",
    "malawi",
    "mali",
    "mauritania",
    "mauritius",
    "morocco",
    "mozambique",
    "namibia",
    "niger",
    "nigeria",
    "rwanda",
    "sao tome and principe",
    "senegal",
    "seychelles",
    "sierra leone",
    "somalia",
    "south africa",
    "south sudan",
    "sudan",
    "tanzania",
    "togo",
    "tunisia",
    "uganda",
    "zambia",
    "zimbabwe",
  ],
};

export default regionsData;
