import "./globals.css";
import AuthProvider from "@/lib/store/AuthProvider";
import ErrorMsg from "@/components/ErrorMsg";
import NavigationWrapper from "@/layout/navigation/NavigationWrapper";
import SideBar from "@/layout/navigation/side/SideBar";
import Footer from "@/layout/footer/Footer";
import { StoreProvider } from "@/lib/store/StoreProvider";

export const metadata = {
  title: "HyperLead | Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <AuthProvider>
        <html lang="en">
          <body className="center flex-col">
            <main className="relative w-full max-w-[1650px]">
              <NavigationWrapper />
              {children}
              <ErrorMsg />
              <SideBar />
              <Footer />
            </main>
          </body>
        </html>
      </AuthProvider>
    </StoreProvider>
  );
}
