import "./globals.css";
import Navigation from "../layout/navigation/Navigation";
import SideBar from "@/layout/navigation/side/SideBar";
import Footer from "@/layout/footer/Footer";
import { StoreProvider } from "@/lib/store/StoreProvides";

export const metadata = {
  title: "HyperLead",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="center flex-col">
          <main className="relative w-full max-w-[1650px]">
            <Navigation />
            {children}
            <SideBar />
            <Footer />
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
