import ReactCountryFlag from "react-country-flag";

// Function to convert country names to ISO codes
export const getCountryCode = (countryName) => {
  const countryMap = {
    "united states": "US",
    "united kingdom": "GB",
    netherlands: "NL",
    germany: "DE",
    france: "FR",
    spain: "ES",
    italy: "IT",
    sweden: "SE",
    norway: "NO",
    denmark: "DK",
    finland: "FI",
    belgium: "BE",
    switzerland: "CH",
    austria: "AT",
    ireland: "IE",
    portugal: "PT",
    greece: "GR",
    poland: "PL",
    "czech republic": "CZ",
    hungary: "HU",
    romania: "RO",
    bulgaria: "BG",
    croatia: "HR",
    slovakia: "SK",
    slovenia: "SI",
    estonia: "EE",
    latvia: "LV",
    lithuania: "LT",
    luxembourg: "LU",
    malta: "MT",
    cyprus: "CY",
    australia: "AU",
    "new zealand": "NZ",
    canada: "CA",
    mexico: "MX",
    brazil: "BR",
    argentina: "AR",
    chile: "CL",
    colombia: "CO",
    peru: "PE",
    venezuela: "VE",
    ecuador: "EC",
    bolivia: "BO",
    paraguay: "PY",
    uruguay: "UY",
    japan: "JP",
    "south korea": "KR",
    china: "CN",
    india: "IN",
    singapore: "SG",
    malaysia: "MY",
    thailand: "TH",
    vietnam: "VN",
    indonesia: "ID",
    philippines: "PH",
    "hong kong": "HK",
    taiwan: "TW",
    israel: "IL",
    uae: "AE",
    "saudi arabia": "SA",
    qatar: "QA",
    kuwait: "KW",
    bahrain: "BH",
    oman: "OM",
    "south africa": "ZA",
    nigeria: "NG",
    egypt: "EG",
    morocco: "MA",
    tunisia: "TN",
    algeria: "DZ",
    kenya: "KE",
    ghana: "GH",
    ethiopia: "ET",
    tanzania: "TZ",
    uganda: "UG",
    rwanda: "RW",
    senegal: "SN",
    "cote d'ivoire": "CI",
    cameroon: "CM",
    angola: "AO",
    mozambique: "MZ",
    zambia: "ZM",
    zimbabwe: "ZW",
    botswana: "BW",
    namibia: "NA",
    madagascar: "MG",
    mauritius: "MU",
    seychelles: "SC",
    comoros: "KM",
    djibouti: "DJ",
    eritrea: "ER",
    somalia: "SO",
    sudan: "SD",
    "south sudan": "SS",
    chad: "TD",
    niger: "NE",
    mali: "ML",
    "burkina faso": "BF",
    benin: "BJ",
    togo: "TG",
    liberia: "LR",
    "sierra leone": "SL",
    guinea: "GN",
    "guinea-bissau": "GW",
    gambia: "GM",
    "cape verde": "CV",
    "sao tome and principe": "ST",
    "equatorial guinea": "GQ",
    gabon: "GA",
    congo: "CG",
    "democratic republic of the congo": "CD",
    "central african republic": "CF",
    burundi: "BI",
    malawi: "MW",
    lesotho: "LS",
    eswatini: "SZ",
    mauritania: "MR",
    "western sahara": "EH",
    libya: "LY",
    lebanon: "LB",
    jordan: "JO",
    syria: "SY",
    iraq: "IQ",
    iran: "IR",
    afghanistan: "AF",
    pakistan: "PK",
    bangladesh: "BD",
    "sri lanka": "LK",
    nepal: "NP",
    bhutan: "BT",
    myanmar: "MM",
    laos: "LA",
    cambodia: "KH",
    brunei: "BN",
    "east timor": "TL",
    "papua new guinea": "PG",
    fiji: "FJ",
    "solomon islands": "SB",
    vanuatu: "VU",
    samoa: "WS",
    tonga: "TO",
    kiribati: "KI",
    tuvalu: "TV",
    nauru: "NR",
    "marshall islands": "MH",
    palau: "PW",
    micronesia: "FM",
    "northern mariana islands": "MP",
    guam: "GU",
    "american samoa": "AS",
    "cook islands": "CK",
    niue: "NU",
    tokelau: "TK",
    "wallis and futuna": "WF",
    "french polynesia": "PF",
    "new caledonia": "NC",
    "pitcairn islands": "PN",
    "norfolk island": "NF",
    "christmas island": "CX",
    "cocos islands": "CC",
    "heard island and mcdonald islands": "HM",
    "french southern territories": "TF",
    "british indian ocean territory": "IO",
    "south georgia and the south sandwich islands": "GS",
    "bouvet island": "BV",
    antarctica: "AQ",
  };

  return countryMap[countryName.toLowerCase()] || "US";
};

// Country Flag Component
export const CountryFlags = ({ countryName, className, style }) => {
  if (!countryName) return null;

  const countryCode = getCountryCode(countryName);
  return (
    <ReactCountryFlag
      className={className}
      countryCode={countryCode}
      svg
      style={style}
      title={countryName}
    />
  );
};
